/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param name From Google Knowledge Graph
 * @param imageUrl Knowledge Graph portrait, falling back to Wikipedia thumbnail
 * @param extract Wikipedia summary extract
 */
@Serializable

data class AuthorInfoDto (

    /* From Google Knowledge Graph */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* Knowledge Graph portrait, falling back to Wikipedia thumbnail */
    @SerialName(value = "imageUrl") val imageUrl: kotlin.String? = null,

    /* Wikipedia summary extract */
    @SerialName(value = "extract") val extract: kotlin.String? = null

) {


}

