/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param externalGoogleId 
 * @param title 
 * @param authors 
 * @param imageUrl 
 * @param publishedDate 
 */
@Serializable

data class AuthorBookDto (

    @SerialName(value = "externalGoogleId") @Required val externalGoogleId: kotlin.String,

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "authors") @Required val authors: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "imageUrl") val imageUrl: kotlin.String? = null,

    @SerialName(value = "publishedDate") val publishedDate: kotlin.String? = null

) {


}

