/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param thumbnail 
 * @param small 
 * @param medium 
 * @param large 
 * @param extraLarge 
 */
@Serializable

data class BookVolumeInfoImageLinksDto (

    @SerialName(value = "thumbnail") @Required val thumbnail: kotlin.String?,

    @SerialName(value = "small") @Required val small: kotlin.String?,

    @SerialName(value = "medium") @Required val medium: kotlin.String?,

    @SerialName(value = "large") @Required val large: kotlin.String?,

    @SerialName(value = "extraLarge") @Required val extraLarge: kotlin.String?

) {


}

