/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.BookDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param success 
 * @param book 
 * @param created False if an existing book (matched by external_google_id) was returned instead of created.
 * @param message 
 */
@Serializable@Serializable

data class BookRegistrationResponseDto (

    @SerialName(value = "success") val success: kotlin.Boolean? = null,

    @SerialName(value = "book") val book: BookDto? = null,

    /* False if an existing book (matched by external_google_id) was returned instead of created. */
    @SerialName(value = "created") val created: kotlin.Boolean? = null,

    @SerialName(value = "message") val message: kotlin.String? = null

) {


}

