/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.BookIndustryIdentifierDto
import com.ivangarzab.kluvs.api.models.BookVolumeInfoImageLinksDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param title 
 * @param authors 
 * @param industryIdentifiers 
 * @param pageCount 
 * @param categories 
 * @param imageLinks 
 * @param subtitle 
 * @param publisher 
 * @param publishedDate 
 * @param description 
 * @param language 
 */
@Serializable

data class BookVolumeInfoDto (

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "authors") @Required val authors: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "industryIdentifiers") @Required val industryIdentifiers: kotlin.collections.List<BookIndustryIdentifierDto>,

    @SerialName(value = "pageCount") @Required val pageCount: kotlin.Int,

    @SerialName(value = "categories") @Required val categories: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "imageLinks") @Required val imageLinks: BookVolumeInfoImageLinksDto,

    @SerialName(value = "subtitle") val subtitle: kotlin.String? = null,

    @SerialName(value = "publisher") val publisher: kotlin.String? = null,

    @SerialName(value = "publishedDate") val publishedDate: kotlin.String? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "language") val language: kotlin.String? = null

) {


}

