/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.BookDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response for ?q= search queries.
 *
 * @param success 
 * @param books 
 * @param total Google Books' estimated corpus count (not the number of items returned on this page — use books.length for that). Approximate; Google caps actual delivery at ~1,000 items regardless of the reported total.
 */
@Serializable@Serializable

data class BookSearchResponseDto (

    @SerialName(value = "success") val success: kotlin.Boolean? = null,

    @SerialName(value = "books") val books: kotlin.collections.List<BookDto>? = null,

    /* Google Books' estimated corpus count (not the number of items returned on this page — use books.length for that). Approximate; Google caps actual delivery at ~1,000 items regardless of the reported total. */
    @SerialName(value = "total") val total: kotlin.Int? = null

) {


}

