/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A lightweight book reference as embedded within a reading progress entry.
 *
 * @param id 
 * @param title 
 * @param pageCount 
 * @param imageUrl 
 */
@Serializable

data class BookSummaryDto (

    @SerialName(value = "id") val id: kotlin.Int? = null,

    @SerialName(value = "title") val title: kotlin.String? = null,

    @SerialName(value = "page_count") val pageCount: kotlin.Int? = null,

    @SerialName(value = "image_url") val imageUrl: kotlin.String? = null

) {


}

