/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param type 
 * @param identifier 
 */
@Serializable

data class BookIndustryIdentifierDto (

    @SerialName(value = "type") @Required val type: BookIndustryIdentifierDto.Type,

    @SerialName(value = "identifier") @Required val identifier: kotlin.String

) {

    /**
     * 
     *
     * Values: ISBN_10,ISBN_13,ISSN,OTHER
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "ISBN_10") ISBN_10("ISBN_10"),
        @SerialName(value = "ISBN_13") ISBN_13("ISBN_13"),
        @SerialName(value = "ISSN") ISSN("ISSN"),
        @SerialName(value = "OTHER") OTHER("OTHER");
    }

}

