/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param title 
 * @param author 
 * @param externalGoogleId Google Books volume ID (recommended for deduplication)
 * @param edition 
 * @param year 
 * @param isbn 
 * @param pageCount 
 * @param imageUrl 
 */
@Serializable@Serializable

data class BookPostRequestDto (

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "author") @Required val author: kotlin.String,

    /* Google Books volume ID (recommended for deduplication) */
    @SerialName(value = "external_google_id") val externalGoogleId: kotlin.String? = null,

    @SerialName(value = "edition") val edition: kotlin.String? = null,

    @SerialName(value = "year") val year: kotlin.Int? = null,

    @SerialName(value = "isbn") val isbn: kotlin.String? = null,

    @SerialName(value = "page_count") val pageCount: kotlin.Int? = null,

    @SerialName(value = "image_url") val imageUrl: kotlin.String? = null

) {


}

