/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.AuthorBookDto
import com.ivangarzab.kluvs.api.models.AuthorInfoDto
import com.ivangarzab.kluvs.api.models.BookVolumeInfoDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param volumeInfo 
 * @param authorInfo 
 * @param authorBooks 
 */
@Serializable

data class BookEnrichmentResponseDto (

    @SerialName(value = "volumeInfo") @Required val volumeInfo: BookVolumeInfoDto,

    @SerialName(value = "authorInfo") @Required val authorInfo: AuthorInfoDto,

    @SerialName(value = "authorBooks") @Required val authorBooks: kotlin.collections.List<AuthorBookDto>

) {


}

