/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.ClubActiveSessionInputDto
import com.ivangarzab.kluvs.api.models.MemberDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param name 
 * @param serverId Optional Discord Server ID.
 * @param discordChannel 
 * @param foundedDate 
 * @param members 
 * @param activeSession 
 * @param shameList List of Member IDs to immediately add to the shame list.
 */
@Serializable

data class ClubCreateRequestDto (

    @SerialName(value = "name") @Required val name: kotlin.String,

    /* Optional Discord Server ID. */
    @SerialName(value = "server_id") val serverId: kotlin.String? = null,

    @SerialName(value = "discord_channel") val discordChannel: kotlin.String? = null,

    @SerialName(value = "founded_date") val foundedDate: kotlin.String? = null,

    @SerialName(value = "members") val members: kotlin.collections.List<MemberDto>? = null,

    @SerialName(value = "active_session") val activeSession: ClubActiveSessionInputDto? = null,

    /* List of Member IDs to immediately add to the shame list. */
    @SerialName(value = "shame_list") val shameList: kotlin.collections.List<kotlin.Int>? = null

) {


}

