/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.ClubDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param success 
 * @param message 
 * @param club 
 * @param clubUpdated Whether the clubs table row was updated.
 * @param shameListUpdated Whether the shame list membership changed.
 */
@Serializable

data class ClubUpdateResponseDto (

    @SerialName(value = "success") val success: kotlin.Boolean? = null,

    @SerialName(value = "message") val message: kotlin.String? = null,

    @SerialName(value = "club") val club: ClubDto? = null,

    /* Whether the clubs table row was updated. */
    @SerialName(value = "club_updated") val clubUpdated: kotlin.Boolean? = null,

    /* Whether the shame list membership changed. */
    @SerialName(value = "shame_list_updated") val shameListUpdated: kotlin.Boolean? = null

) {


}

