/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.BookDto
import com.ivangarzab.kluvs.api.models.DiscussionDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Immediately start a session for this club.
 *
 * @param id 
 * @param dueDate 
 * @param book 
 * @param discussions 
 */
@Serializable@Serializable

data class ClubPostRequestActiveSessionDto (

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "due_date") val dueDate: kotlin.String? = null,

    @SerialName(value = "book") val book: BookDto? = null,

    @SerialName(value = "discussions") val discussions: kotlin.collections.List<DiscussionDto>? = null

) {


}

