/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param clubId 
 * @param token Shareable invite token used in invite URLs
 * @param createdAt 
 * @param useCount 
 * @param isActive 
 * @param createdBy Member ID who created the invite
 * @param expiresAt NULL = never expires
 * @param maxUses NULL = unlimited
 */
@Serializable@Serializable

data class ClubInvite (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "club_id") @Required val clubId: kotlin.String,

    /* Shareable invite token used in invite URLs */
    @SerialName(value = "token") @Required val token: kotlin.String,

    @SerialName(value = "created_at") @Required val createdAt: kotlin.String,

    @SerialName(value = "use_count") @Required val useCount: kotlin.Int = 0,

    @SerialName(value = "is_active") @Required val isActive: kotlin.Boolean = true,

    /* Member ID who created the invite */
    @SerialName(value = "created_by") val createdBy: kotlin.Int? = null,

    /* NULL = never expires */
    @SerialName(value = "expires_at") val expiresAt: kotlin.String? = null,

    /* NULL = unlimited */
    @SerialName(value = "max_uses") val maxUses: kotlin.Int? = null

) {


}

