/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param discordChannel 
 * @param foundedDate 
 * @param serverId 
 * @param joinPolicy Controls how members can join the club. Setting to INVITE_LINK creates (or reuses) an active club invite token; setting to PRIVATE deactivates all active invites for the club. 
 * @param shameList 
 */
@Serializable@Serializable

data class ClubUpdateRequestDto (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "discord_channel") val discordChannel: kotlin.String? = null,

    @SerialName(value = "founded_date") val foundedDate: kotlin.String? = null,

    @SerialName(value = "server_id") val serverId: kotlin.String? = null,

    /* Controls how members can join the club. Setting to INVITE_LINK creates (or reuses) an active club invite token; setting to PRIVATE deactivates all active invites for the club.  */
    @SerialName(value = "join_policy") val joinPolicy: ClubUpdateRequestDto.JoinPolicy? = null,

    @SerialName(value = "shame_list") val shameList: kotlin.collections.List<kotlin.Int>? = null

) {

    /**
     * Controls how members can join the club. Setting to INVITE_LINK creates (or reuses) an active club invite token; setting to PRIVATE deactivates all active invites for the club. 
     *
     * Values: PRIVATE,INVITE_LINK
     */
    @Serializable
    enum class JoinPolicy(val value: kotlin.String) {
        @SerialName(value = "PRIVATE") PRIVATE("PRIVATE"),
        @SerialName(value = "INVITE_LINK") INVITE_LINK("INVITE_LINK");
    }

}

