/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Standard delete acknowledgement, reused across all DELETE endpoints.
 *
 * @param success 
 * @param message 
 * @param warning Present if the deletion had a non-fatal side effect.
 */
@Serializable

data class DeleteResponseDto (

    @SerialName(value = "success") @Required val success: kotlin.Boolean,

    @SerialName(value = "message") @Required val message: kotlin.String,

    /* Present if the deletion had a non-fatal side effect. */
    @SerialName(value = "warning") val warning: kotlin.String? = null

) {


}

