/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param discussionId 
 * @param memberId 
 * @param content 
 * @param visibility 
 * @param createdAt 
 * @param updatedAt 
 */
@Serializable@Serializable

data class DiscussionNote (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "discussion_id") @Required val discussionId: kotlin.String,

    @SerialName(value = "member_id") @Required val memberId: kotlin.Int,

    @SerialName(value = "content") @Required val content: kotlin.String,

    @SerialName(value = "visibility") @Required val visibility: DiscussionNote.Visibility = Visibility.`private`,

    @SerialName(value = "created_at") @Required val createdAt: kotlin.String,

    @SerialName(value = "updated_at") @Required val updatedAt: kotlin.String

) {

    /**
     * 
     *
     * Values: `private`,`public`
     */
    @Serializable
    enum class Visibility(val value: kotlin.String) {
        @SerialName(value = "private") `private`("private"),
        @SerialName(value = "public") `public`("public");
    }

}

