/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param sessionId 
 * @param title 
 * @param scheduledAt 
 * @param location 
 */
@Serializable@Serializable

data class DiscussionCreateRequestDto (

    @SerialName(value = "session_id") @Required val sessionId: kotlin.String,

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "scheduled_at") @Required val scheduledAt: kotlin.String,

    @SerialName(value = "location") val location: kotlin.String? = null

) {


}

