/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param discussionId 
 * @param memberId 
 * @param status 
 * @param updatedAt 
 */
@Serializable@Serializable

data class DiscussionAttendancePost200ResponseDto (

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "discussion_id") val discussionId: kotlin.String? = null,

    @SerialName(value = "member_id") val memberId: kotlin.Int? = null,

    @SerialName(value = "status") val status: DiscussionAttendancePost200ResponseDto.Status? = null,

    @SerialName(value = "updated_at") val updatedAt: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: yes,no,maybe
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "yes") yes("yes"),
        @SerialName(value = "no") no("no"),
        @SerialName(value = "maybe") maybe("maybe");
    }

}

