/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param sessionId 
 * @param title 
 * @param scheduledAt ISO 8601 timestamp (with timezone offset) for the discussion
 * @param location Discussion location or platform
 */
@Serializable

data class DiscussionDto (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "session_id") @Required val sessionId: kotlin.String,

    @SerialName(value = "title") @Required val title: kotlin.String,

    /* ISO 8601 timestamp (with timezone offset) for the discussion */
    @SerialName(value = "scheduled_at") @Required val scheduledAt: kotlin.String,

    /* Discussion location or platform */
    @SerialName(value = "location") val location: kotlin.String? = null

) {


}

