/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.DiscussionAttendanceRosterEntryDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param responses One entry per club member who has responded; members with no entry have not responded.
 * @param myStatus The calling member's own RSVP response (null if they have not responded).
 * @param totalMembers Total member count of the discussion's club
 */
@Serializable

data class DiscussionAttendanceRosterResponseDto (

    /* One entry per club member who has responded; members with no entry have not responded. */
    @SerialName(value = "responses") @Required val responses: kotlin.collections.List<DiscussionAttendanceRosterEntryDto>,

    /* The calling member's own RSVP response (null if they have not responded). */
    @SerialName(value = "my_status") @Required val myStatus: DiscussionAttendanceRosterResponseDto.MyStatus?,

    /* Total member count of the discussion's club */
    @SerialName(value = "total_members") @Required val totalMembers: kotlin.Int

) {

    /**
     * The calling member's own RSVP response (null if they have not responded).
     *
     * Values: yes,no,maybe
     */
    @Serializable
    enum class MyStatus(val value: kotlin.String) {
        @SerialName(value = "yes") yes("yes"),
        @SerialName(value = "no") no("no"),
        @SerialName(value = "maybe") maybe("maybe");
    }

}

