/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param discussionId 
 * @param status 
 */
@Serializable@Serializable

data class DiscussionAttendancePostRequestDto (

    @SerialName(value = "discussion_id") @Required val discussionId: kotlin.String,

    @SerialName(value = "status") @Required val status: DiscussionAttendancePostRequestDto.Status

) {

    /**
     * 
     *
     * Values: yes,no,maybe
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "yes") yes("yes"),
        @SerialName(value = "no") no("no"),
        @SerialName(value = "maybe") maybe("maybe");
    }

}

