/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.DiscussionAttendanceDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Best-effort reconstruction based on the endpoint description (\"the roster, the caller's own status, and the club's total member count\") — the spec did not document an exact shape; verify against the real backend response before relying on this.
 *
 * @param attendees 
 * @param myStatus 
 * @param memberCount Total member count of the discussion's club
 */
@Serializable@Serializable

data class DiscussionAttendanceRosterResponseDto (

    @SerialName(value = "attendees") val attendees: kotlin.collections.List<DiscussionAttendanceDto>? = null,

    @SerialName(value = "my_status") val myStatus: DiscussionAttendanceRosterResponseDto.MyStatus? = null,

    /* Total member count of the discussion's club */
    @SerialName(value = "member_count") val memberCount: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: yes,no,maybe
     */
    @Serializable
    enum class MyStatus(val value: kotlin.String) {
        @SerialName(value = "yes") yes("yes"),
        @SerialName(value = "no") no("no"),
        @SerialName(value = "maybe") maybe("maybe");
    }

}

