/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param title 
 * @param scheduledAt 
 * @param location 
 */
@Serializable@Serializable

data class DiscussionUpdateRequestDto (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "title") val title: kotlin.String? = null,

    @SerialName(value = "scheduled_at") val scheduledAt: kotlin.String? = null,

    @SerialName(value = "location") val location: kotlin.String? = null

) {


}

