/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param memberId 
 * @param name Member name (null if the member row could not be joined).
 * @param status RSVP response
 */
@Serializable

data class DiscussionAttendanceRosterEntryDto (

    @SerialName(value = "member_id") @Required val memberId: kotlin.Int,

    /* Member name (null if the member row could not be joined). */
    @SerialName(value = "name") @Required val name: kotlin.String?,

    /* RSVP response */
    @SerialName(value = "status") @Required val status: DiscussionAttendanceRosterEntryDto.Status

) {

    /**
     * RSVP response
     *
     * Values: yes,no,maybe
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "yes") yes("yes"),
        @SerialName(value = "no") no("no"),
        @SerialName(value = "maybe") maybe("maybe");
    }

}

