/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param discussionId 
 * @param memberId 
 * @param status RSVP response
 * @param updatedAt 
 */
@Serializable@Serializable

data class DiscussionAttendance (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "discussion_id") @Required val discussionId: kotlin.String,

    @SerialName(value = "member_id") @Required val memberId: kotlin.Int,

    /* RSVP response */
    @SerialName(value = "status") @Required val status: DiscussionAttendance.Status,

    @SerialName(value = "updated_at") @Required val updatedAt: kotlin.String

) {

    /**
     * RSVP response
     *
     * Values: yes,no,maybe
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "yes") yes("yes"),
        @SerialName(value = "no") no("no"),
        @SerialName(value = "maybe") maybe("maybe");
    }

}

