/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.BookDto
import com.ivangarzab.kluvs.api.models.DiscussionDto
import com.ivangarzab.kluvs.api.models.SessionDto
import com.ivangarzab.kluvs.api.models.SessionParticipantSummaryDto
import com.ivangarzab.kluvs.api.models.SessionReadingLogGroupsDto
import com.ivangarzab.kluvs.api.models.SessionReadingLogResponseDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param clubId 
 * @param status Lifecycle status of the session.
 * @param success 
 * @param readingLog 
 * @param bookId 
 * @param book 
 * @param dueDate 
 * @param discussions 
 * @param members Participation roster, as embedded within a club response's active_session.
 */
@Serializable

data class GetSessions200ResponseDto (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "club_id") @Required val clubId: kotlin.String,

    /* Lifecycle status of the session. */
    @SerialName(value = "status") @Required val status: GetSessions200ResponseDto.Status,

    @SerialName(value = "success") val success: kotlin.Boolean? = null,

    @SerialName(value = "reading_log") val readingLog: SessionReadingLogGroupsDto? = null,

    @SerialName(value = "book_id") val bookId: kotlin.Int? = null,

    @SerialName(value = "book") val book: BookDto? = null,

    @SerialName(value = "due_date") val dueDate: kotlin.String? = null,

    @SerialName(value = "discussions") val discussions: kotlin.collections.List<DiscussionDto>? = null,

    /* Participation roster, as embedded within a club response's active_session. */
    @SerialName(value = "members") val members: kotlin.collections.List<SessionParticipantSummaryDto>? = null

) {

    /**
     * Lifecycle status of the session.
     *
     * Values: active,finished
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "active") active("active"),
        @SerialName(value = "finished") finished("finished");
    }

}

