/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.ClubPreviewDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param valid 
 * @param club 
 */
@Serializable@Serializable

data class JoinPreviewResponseDto (

    @SerialName(value = "valid") val valid: kotlin.Boolean? = null,

    @SerialName(value = "club") val club: ClubPreviewDto? = null

) {


}

