/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param success 
 * @param liked New state after toggle (true = just liked, false = just unliked)
 */
@Serializable@Serializable

data class LikePost200ResponseDto (

    @SerialName(value = "success") val success: kotlin.Boolean? = null,

    /* New state after toggle (true = just liked, false = just unliked) */
    @SerialName(value = "liked") val liked: kotlin.Boolean? = null

) {


}

