/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * add_to_club response
 *
 * @param success 
 * @param memberId 
 * @param clubId 
 */
@Serializable@Serializable

data class MemberPut200ResponseOneOf1Dto (

    @SerialName(value = "success") val success: kotlin.Boolean? = null,

    @SerialName(value = "member_id") val memberId: kotlin.Int? = null,

    @SerialName(value = "club_id") val clubId: kotlin.String? = null

) {


}

