/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*

/**
 * Valid roles assignable via club_roles (owner cannot be assigned or changed via this endpoint).
 *
 * Values: admin,member
 */
@Serializable@Serializable
enum class MemberAssignableRoleDto(val value: kotlin.String) {

    @SerialName(value = "admin")
    admin("admin"),

    @SerialName(value = "member")
    member("member");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is MemberAssignableRoleDto) "$data" else null

        /**
         * Returns a valid [MemberAssignableRoleDto] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): MemberAssignableRoleDto? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


