/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id The ID of the member to update (or the target member for add_to_club).
 * @param name 
 * @param booksRead 
 * @param handle 
 * @param avatarPath Storage path of the member's avatar. Must start with `{id}/` (e.g. `42/avatar.png`). Pass null to clear the avatar. 
 * @param discordId Discord user snowflake ID. Pass null to clear it.
 * @param platformMetadata Flexible JSON object for platform-specific data. Replaces the entire field — callers must Read-Modify-Write.
 * @param clubs Full list of Club IDs this member should belong to. Diffed against existing to add/remove.
 * @param clubRoles Map of club_id → role to update per-club roles. Valid roles are admin and member (owner cannot be assigned or changed via this endpoint).
 * @param addToClub Club ID to add the target member (`id`) to. When present, all other update fields are ignored. The calling user's JWT must belong to a member who is an admin or owner of the target club. The target member is added with the `member` role. 
 */
@Serializable@Serializable

data class MemberPutRequestDto (

    /* The ID of the member to update (or the target member for add_to_club). */
    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "books_read") val booksRead: kotlin.Int? = null,

    @SerialName(value = "handle") val handle: kotlin.String? = null,

    /* Storage path of the member's avatar. Must start with `{id}/` (e.g. `42/avatar.png`). Pass null to clear the avatar.  */
    @SerialName(value = "avatar_path") val avatarPath: kotlin.String? = null,

    /* Discord user snowflake ID. Pass null to clear it. */
    @SerialName(value = "discord_id") val discordId: kotlin.String? = null,

    /* Flexible JSON object for platform-specific data. Replaces the entire field — callers must Read-Modify-Write. */
    @SerialName(value = "platform_metadata") val platformMetadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Full list of Club IDs this member should belong to. Diffed against existing to add/remove. */
    @SerialName(value = "clubs") val clubs: kotlin.collections.List<kotlin.String>? = null,

    /* Map of club_id → role to update per-club roles. Valid roles are admin and member (owner cannot be assigned or changed via this endpoint). */
    @SerialName(value = "club_roles") val clubRoles: MemberPutRequestDto.ClubRoles? = null,

    /* Club ID to add the target member (`id`) to. When present, all other update fields are ignored. The calling user's JWT must belong to a member who is an admin or owner of the target club. The target member is added with the `member` role.  */
    @SerialName(value = "add_to_club") val addToClub: kotlin.String? = null

) {

    /**
     * Map of club_id → role to update per-club roles. Valid roles are admin and member (owner cannot be assigned or changed via this endpoint).
     *
     * Values: admin,member
     */
    @Serializable
    enum class ClubRoles(val value: kotlin.String) {
        @SerialName(value = "admin") admin("admin"),
        @SerialName(value = "member") member("member");
    }

}

