/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.MemberClubsInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id Internal member ID
 * @param name 
 * @param platformMetadata Flexible JSON object for platform-specific data (e.g., Discord Top.gg votes).
 * @param booksRead 
 * @param handle Discord handle or username
 * @param avatarPath 
 * @param userId Linked Supabase Auth User ID
 * @param discordId Discord user snowflake ID. Stored as TEXT to preserve JSON precision.
 * @param createdAt 
 * @param clubs Clubs this member belongs to, each with their per-club role.
 */
@Serializable@Serializable

data class Member (

    /* Internal member ID */
    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    /* Flexible JSON object for platform-specific data (e.g., Discord Top.gg votes). */
    @SerialName(value = "platform_metadata") @Required val platformMetadata: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    @SerialName(value = "books_read") val booksRead: kotlin.Int? = 0,

    /* Discord handle or username */
    @SerialName(value = "handle") val handle: kotlin.String? = null,

    @SerialName(value = "avatar_path") val avatarPath: kotlin.String? = null,

    /* Linked Supabase Auth User ID */
    @SerialName(value = "user_id") val userId: kotlin.String? = null,

    /* Discord user snowflake ID. Stored as TEXT to preserve JSON precision. */
    @SerialName(value = "discord_id") val discordId: kotlin.String? = null,

    @SerialName(value = "created_at") val createdAt: kotlin.String? = null,

    /* Clubs this member belongs to, each with their per-club role. */
    @SerialName(value = "clubs") val clubs: kotlin.collections.List<MemberClubsInner>? = null

) {


}

