/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.ClubMemberDto
import com.ivangarzab.kluvs.api.models.PastSessionDto
import com.ivangarzab.kluvs.api.models.SessionDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A club embedded within a member's `clubs` list, including the member's per-club role.
 *
 * @param id 
 * @param name 
 * @param joinPolicy Controls how new members can join. PRIVATE = by admin only; INVITE_LINK = anyone with the link.
 * @param discordChannel Discord channel ID
 * @param serverId Parent server ID
 * @param foundedDate 
 * @param inviteToken Active invite token UUID (present when join_policy is INVITE_LINK, null otherwise).
 * @param members Club members with their per-club role.
 * @param activeSession 
 * @param pastSessions 
 * @param shameList Array of member IDs on shame list
 * @param role Member's role in this specific club
 */
@Serializable@Serializable

data class MemberClubEntryDto (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    /* Controls how new members can join. PRIVATE = by admin only; INVITE_LINK = anyone with the link. */
    @SerialName(value = "join_policy") @Required val joinPolicy: MemberClubEntryDto.JoinPolicy = JoinPolicy.PRIVATE,

    /* Discord channel ID */
    @SerialName(value = "discord_channel") val discordChannel: kotlin.String? = null,

    /* Parent server ID */
    @SerialName(value = "server_id") val serverId: kotlin.String? = null,

    @SerialName(value = "founded_date") val foundedDate: kotlin.String? = null,

    /* Active invite token UUID (present when join_policy is INVITE_LINK, null otherwise). */
    @SerialName(value = "invite_token") val inviteToken: kotlin.String? = null,

    /* Club members with their per-club role. */
    @SerialName(value = "members") val members: kotlin.collections.List<ClubMemberDto>? = null,

    @SerialName(value = "active_session") val activeSession: SessionDto? = null,

    @SerialName(value = "past_sessions") val pastSessions: kotlin.collections.List<PastSessionDto>? = null,

    /* Array of member IDs on shame list */
    @SerialName(value = "shame_list") val shameList: kotlin.collections.List<kotlin.Int>? = null,

    /* Member's role in this specific club */
    @SerialName(value = "role") val role: MemberClubEntryDto.Role? = null

) {

    /**
     * Controls how new members can join. PRIVATE = by admin only; INVITE_LINK = anyone with the link.
     *
     * Values: PRIVATE,INVITE_LINK
     */
    @Serializable
    enum class JoinPolicy(val value: kotlin.String) {
        @SerialName(value = "PRIVATE") PRIVATE("PRIVATE"),
        @SerialName(value = "INVITE_LINK") INVITE_LINK("INVITE_LINK");
    }
    /**
     * Member's role in this specific club
     *
     * Values: owner,admin,member
     */
    @Serializable
    enum class Role(val value: kotlin.String) {
        @SerialName(value = "owner") owner("owner"),
        @SerialName(value = "admin") admin("admin"),
        @SerialName(value = "member") member("member");
    }

}

