/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param name 
 * @param clubs Array of Club IDs this member belongs to. Optional, but if present must contain at least one club ID (an empty array is rejected). 
 * @param booksRead 
 * @param handle Optional Discord handle or username.
 * @param avatarPath Path to the avatar image in storage.
 * @param discordId Discord user snowflake ID. Stored as text to preserve precision.
 * @param platformMetadata Flexible JSON object for platform-specific data (e.g., Discord Top.gg votes). Defaults to {}.
 * @param id Optional explicit ID. Omit to let the DB sequence assign one.
 */
@Serializable@Serializable

data class MemberCreateRequestDto (

    @SerialName(value = "name") @Required val name: kotlin.String,

    /* Array of Club IDs this member belongs to. Optional, but if present must contain at least one club ID (an empty array is rejected).  */
    @SerialName(value = "clubs") val clubs: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "books_read") val booksRead: kotlin.Int? = 0,

    /* Optional Discord handle or username. */
    @SerialName(value = "handle") val handle: kotlin.String? = null,

    /* Path to the avatar image in storage. */
    @SerialName(value = "avatar_path") val avatarPath: kotlin.String? = null,

    /* Discord user snowflake ID. Stored as text to preserve precision. */
    @SerialName(value = "discord_id") val discordId: kotlin.String? = null,

    /* Flexible JSON object for platform-specific data (e.g., Discord Top.gg votes). Defaults to {}. */
    @SerialName(value = "platform_metadata") val platformMetadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Optional explicit ID. Omit to let the DB sequence assign one. */
    @SerialName(value = "id") val id: kotlin.Int? = null

) {


}

