/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Standard update response
 *
 * @param success 
 * @param message 
 * @param member 
 * @param clubsUpdated 
 * @param rolesUpdated 
 */
@Serializable@Serializable

data class MemberPut200ResponseOneOfDto (

    @SerialName(value = "success") val success: kotlin.Boolean? = null,

    @SerialName(value = "message") val message: kotlin.String? = null,

    @SerialName(value = "member") val member: kotlin.String? = null,

    @SerialName(value = "clubs_updated") val clubsUpdated: kotlin.Boolean? = null,

    @SerialName(value = "roles_updated") val rolesUpdated: kotlin.Boolean? = null

) {


}

