/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.ReadingProgressDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param success 
 * @param progress 
 */
@Serializable@Serializable

data class ProgressListResponseDto (

    @SerialName(value = "success") val success: kotlin.Boolean? = null,

    @SerialName(value = "progress") val progress: kotlin.collections.List<ReadingProgressDto>? = null

) {


}

