/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param progressType 
 * @param currentPage Required when progress_type is page, unless the entry already has one
 * @param percentComplete Required when progress_type is percent, unless the entry already has one
 * @param status 
 */
@Serializable@Serializable

data class ProgressPutRequestDto (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "progress_type") @Required val progressType: ProgressPutRequestDto.ProgressType,

    /* Required when progress_type is page, unless the entry already has one */
    @SerialName(value = "current_page") val currentPage: kotlin.Int? = null,

    /* Required when progress_type is percent, unless the entry already has one */
    @SerialName(value = "percent_complete") val percentComplete: kotlin.Float? = null,

    @SerialName(value = "status") val status: ProgressPutRequestDto.Status? = null

) {

    /**
     * 
     *
     * Values: page,percent
     */
    @Serializable
    enum class ProgressType(val value: kotlin.String) {
        @SerialName(value = "page") page("page"),
        @SerialName(value = "percent") percent("percent");
    }
    /**
     * 
     *
     * Values: in_progress,completed
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "in_progress") in_progress("in_progress"),
        @SerialName(value = "completed") completed("completed");
    }

}

