/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param bookId Local DB book ID
 * @param progressType 
 * @param sessionId Optional session this progress entry is linked to
 * @param currentPage Required if progress_type is 'page'
 * @param percentComplete Required if progress_type is 'percent', 0-100
 */
@Serializable@Serializable

data class ProgressPostRequestDto (

    /* Local DB book ID */
    @SerialName(value = "book_id") @Required val bookId: kotlin.Int,

    @SerialName(value = "progress_type") @Required val progressType: ProgressPostRequestDto.ProgressType,

    /* Optional session this progress entry is linked to */
    @SerialName(value = "session_id") val sessionId: kotlin.String? = null,

    /* Required if progress_type is 'page' */
    @SerialName(value = "current_page") val currentPage: kotlin.Int? = null,

    /* Required if progress_type is 'percent', 0-100 */
    @SerialName(value = "percent_complete") val percentComplete: kotlin.Float? = null

) {

    /**
     * 
     *
     * Values: page,percent
     */
    @Serializable
    enum class ProgressType(val value: kotlin.String) {
        @SerialName(value = "page") page("page"),
        @SerialName(value = "percent") percent("percent");
    }

}

