/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.BookSummaryDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param memberId 
 * @param bookId 
 * @param progressType 
 * @param status 
 * @param startedAt 
 * @param updatedAt 
 * @param sessionId 
 * @param currentPage 
 * @param percentComplete 
 * @param completedAt 
 * @param book 
 */
@Serializable

data class ReadingProgressDto (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "member_id") @Required val memberId: kotlin.Int,

    @SerialName(value = "book_id") @Required val bookId: kotlin.Int,

    @SerialName(value = "progress_type") @Required val progressType: ReadingProgressDto.ProgressType,

    @SerialName(value = "status") @Required val status: ReadingProgressDto.Status,

    @SerialName(value = "started_at") @Required val startedAt: kotlin.String,

    @SerialName(value = "updated_at") @Required val updatedAt: kotlin.String,

    @SerialName(value = "session_id") val sessionId: kotlin.String? = null,

    @SerialName(value = "current_page") val currentPage: kotlin.Int? = null,

    @SerialName(value = "percent_complete") val percentComplete: kotlin.Float? = null,

    @SerialName(value = "completed_at") val completedAt: kotlin.String? = null,

    @SerialName(value = "book") val book: BookSummaryDto? = null

) {

    /**
     * 
     *
     * Values: page,percent
     */
    @Serializable
    enum class ProgressType(val value: kotlin.String) {
        @SerialName(value = "page") page("page"),
        @SerialName(value = "percent") percent("percent");
    }
    /**
     * 
     *
     * Values: in_progress,completed
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "in_progress") in_progress("in_progress"),
        @SerialName(value = "completed") completed("completed");
    }

}

