/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.ServerDto
import com.ivangarzab.kluvs.api.models.ServerGet200ResponseOneOf1Dto
import com.ivangarzab.kluvs.api.models.ServerGet200ResponseOneOfClubsInnerDto
import com.ivangarzab.kluvs.api.models.ServerGet200ResponseOneOfDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param clubs 
 * @param servers 
 */
@Serializable@Serializable

data class ServerGet200ResponseDto (

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "clubs") val clubs: kotlin.collections.List<ServerGet200ResponseOneOfClubsInnerDto>? = null,

    @SerialName(value = "servers") val servers: kotlin.collections.List<ServerDto>? = null

) {


}

