/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Joined book info for the session
 *
 * @param title 
 * @param author 
 */
@Serializable@Serializable

data class ServerClubLatestSessionBookDto (

    @SerialName(value = "title") val title: kotlin.String? = null,

    @SerialName(value = "author") val author: kotlin.String? = null

) {


}

