/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Custom error shape (not the standard Error schema)
 *
 * @param success 
 * @param error 
 * @param clubsCount Number of clubs still associated with this server
 */
@Serializable@Serializable

data class ServerDeleteConflictResponseDto (

    @SerialName(value = "success") val success: kotlin.Boolean? = null,

    @SerialName(value = "error") val error: kotlin.String? = null,

    /* Number of clubs still associated with this server */
    @SerialName(value = "clubs_count") val clubsCount: kotlin.Int? = null

) {


}

