/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.ServerGet200ResponseOneOfClubsInnerDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response when ID is provided (Single Server)
 *
 * @param id 
 * @param name 
 * @param clubs 
 */
@Serializable@Serializable

data class ServerGet200ResponseOneOfDto (

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "clubs") val clubs: kotlin.collections.List<ServerGet200ResponseOneOfClubsInnerDto>? = null

) {


}

