/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param name 
 * @param id Optional Discord Snowflake ID. If omitted, a random ID is generated.
 */
@Serializable

data class ServerCreateRequestDto (

    @SerialName(value = "name") @Required val name: kotlin.String,

    /* Optional Discord Snowflake ID. If omitted, a random ID is generated. */
    @SerialName(value = "id") val id: kotlin.String? = null

) {


}

