/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.ServerGet200ResponseOneOfClubsInnerAllOfLatestSessionBooksDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The club's most recent session by due_date, with nested book title/author, or null if none exist
 *
 * @param id 
 * @param dueDate 
 * @param books 
 */
@Serializable@Serializable

data class ServerGet200ResponseOneOfClubsInnerAllOfLatestSessionDto (

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "due_date") val dueDate: kotlin.String? = null,

    @SerialName(value = "books") val books: ServerGet200ResponseOneOfClubsInnerAllOfLatestSessionBooksDto? = null

) {


}

