/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A member's participation entry on a session, as embedded within a club response's active_session.members. Distinct from SessionMember: this shape carries member_name instead of session_id.
 *
 * @param memberId 
 * @param memberName 
 * @param isReading Whether the member is actively reading (vs. opted out)
 */
@Serializable

data class SessionParticipantSummaryDto (

    @SerialName(value = "member_id") @Required val memberId: kotlin.Int,

    @SerialName(value = "member_name") @Required val memberName: kotlin.String,

    /* Whether the member is actively reading (vs. opted out) */
    @SerialName(value = "is_reading") @Required val isReading: kotlin.Boolean = true

) {


}

