/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.SessionReadingLogEntryDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param active 
 * @param finished 
 */
@Serializable

data class SessionReadingLogGroupsDto (

    @SerialName(value = "active") val active: kotlin.collections.List<SessionReadingLogEntryDto>? = null,

    @SerialName(value = "finished") val finished: kotlin.collections.List<SessionReadingLogEntryDto>? = null

) {


}

