/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param book Whether the associated book was updated
 * @param session Whether session fields (club_id, due_date) were updated
 * @param sessionMembers Whether session_members rows were upserted
 */
@Serializable@Serializable

data class SessionPut200ResponseOneOf2UpdatesDto (

    /* Whether the associated book was updated */
    @SerialName(value = "book") val book: kotlin.Boolean? = null,

    /* Whether session fields (club_id, due_date) were updated */
    @SerialName(value = "session") val session: kotlin.Boolean? = null,

    /* Whether session_members rows were upserted */
    @SerialName(value = "session_members") val sessionMembers: kotlin.Boolean? = null

) {


}

