/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.BookDto
import com.ivangarzab.kluvs.api.models.DiscussionDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param clubId 
 * @param status Lifecycle status of the session.
 * @param bookId 
 * @param book 
 * @param dueDate 
 * @param discussions 
 */
@Serializable

data class SessionDto (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "club_id") @Required val clubId: kotlin.String,

    /* Lifecycle status of the session. */
    @SerialName(value = "status") @Required val status: SessionDto.Status,

    @SerialName(value = "book_id") val bookId: kotlin.Int? = null,

    @SerialName(value = "book") val book: BookDto? = null,

    @SerialName(value = "due_date") val dueDate: kotlin.String? = null,

    @SerialName(value = "discussions") val discussions: kotlin.collections.List<DiscussionDto>? = null,

    /* HAND-EDITED: the club GET response embeds `active_session.members[]`, but the
       OpenAPI spec's Session schema does not declare it yet, so regeneration omits
       this field. Re-apply this edit (or fix the spec) if models are regenerated. */
    @SerialName(value = "members") val members: kotlin.collections.List<SessionParticipantDto>? = null

) {

    /**
     * Lifecycle status of the session.
     *
     * Values: active,finished
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "active") active("active"),
        @SerialName(value = "finished") finished("finished");
    }

}

