/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.SessionReadingLogBookDto
import com.ivangarzab.kluvs.api.models.SessionReadingLogClubDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param dueDate 
 * @param book 
 * @param club 
 */
@Serializable

data class SessionReadingLogEntryDto (

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "due_date") val dueDate: kotlin.String? = null,

    @SerialName(value = "book") val book: SessionReadingLogBookDto? = null,

    @SerialName(value = "club") val club: SessionReadingLogClubDto? = null

) {


}

