/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.SessionDiscussionInputDto
import com.ivangarzab.kluvs.api.models.SessionInlineBookInputDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param clubId The ID of the club hosting this session.
 * @param bookId Preferred. The local DB ID of a pre-registered book (from POST /book).
 * @param dueDate Target date for finishing the book.
 * @param book 
 * @param allReading Controls the default `is_reading` flag for auto-populated session_members rows (one per existing club member). When true (default), all members are marked as reading and their shelf is set to \"currently_reading\" for this book. Set to false to default new session members to not-reading.
 * @param discussions Optional list of discussions to schedule immediately.
 */
@Serializable

data class SessionCreateRequestDto (

    /* The ID of the club hosting this session. */
    @SerialName(value = "club_id") @Required val clubId: kotlin.String,

    /* Preferred. The local DB ID of a pre-registered book (from POST /book). */
    @SerialName(value = "book_id") val bookId: kotlin.Int? = null,

    /* Target date for finishing the book. */
    @SerialName(value = "due_date") val dueDate: kotlin.String? = null,

    @SerialName(value = "book") val book: SessionInlineBookInputDto? = null,

    /* Controls the default `is_reading` flag for auto-populated session_members rows (one per existing club member). When true (default), all members are marked as reading and their shelf is set to \"currently_reading\" for this book. Set to false to default new session members to not-reading. */
    @SerialName(value = "all_reading") val allReading: kotlin.Boolean? = true,

    /* Optional list of discussions to schedule immediately. */
    @SerialName(value = "discussions") val discussions: kotlin.collections.List<SessionDiscussionInputDto>? = null

) {


}

