/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Deprecated. Inline book object. Use book_id instead.
 *
 * @param title 
 * @param author 
 * @param year 
 * @param isbn 
 * @param pageCount 
 */
@Serializable

data class SessionInlineBookInputDto (

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "author") @Required val author: kotlin.String,

    @SerialName(value = "year") val year: kotlin.Int? = null,

    @SerialName(value = "isbn") val isbn: kotlin.String? = null,

    @SerialName(value = "page_count") val pageCount: kotlin.Int? = null

) {


}

