/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param title 
 * @param scheduledAt ISO 8601 timestamp (with timezone offset) for the discussion
 * @param location 
 */
@Serializable@Serializable

data class SessionDiscussionInputDto (

    @SerialName(value = "title") val title: kotlin.String? = null,

    /* ISO 8601 timestamp (with timezone offset) for the discussion */
    @SerialName(value = "scheduled_at") val scheduledAt: kotlin.String? = null,

    @SerialName(value = "location") val location: kotlin.String? = null

) {


}

