/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response when `finish` is true
 *
 * @param success 
 * @param message 
 * @param membersCredited Number of is_reading session_members whose books_read count was incremented
 */
@Serializable@Serializable

data class SessionPut200ResponseOneOfDto (

    @SerialName(value = "success") val success: kotlin.Boolean? = null,

    @SerialName(value = "message") val message: kotlin.String? = null,

    /* Number of is_reading session_members whose books_read count was incremented */
    @SerialName(value = "members_credited") val membersCredited: kotlin.Int? = null

) {


}

