/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.SessionPut200ResponseOneOf1Dto
import com.ivangarzab.kluvs.api.models.SessionPut200ResponseOneOf2Dto
import com.ivangarzab.kluvs.api.models.SessionPut200ResponseOneOf2UpdatesDto
import com.ivangarzab.kluvs.api.models.SessionPut200ResponseOneOfDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param success 
 * @param message 
 * @param membersCredited Number of is_reading session_members whose books_read count was incremented
 * @param updates 
 */
@Serializable@Serializable

data class SessionPut200ResponseDto (

    @SerialName(value = "success") val success: kotlin.Boolean? = null,

    @SerialName(value = "message") val message: kotlin.String? = null,

    /* Number of is_reading session_members whose books_read count was incremented */
    @SerialName(value = "members_credited") val membersCredited: kotlin.Int? = null,

    @SerialName(value = "updates") val updates: SessionPut200ResponseOneOf2UpdatesDto? = null

) {


}

