/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param sessionId 
 * @param memberId 
 * @param isReading Whether the member is actively reading (vs. opted out)
 */
@Serializable@Serializable

data class SessionMember (

    @SerialName(value = "session_id") @Required val sessionId: kotlin.String,

    @SerialName(value = "member_id") @Required val memberId: kotlin.Int,

    /* Whether the member is actively reading (vs. opted out) */
    @SerialName(value = "is_reading") @Required val isReading: kotlin.Boolean = true

) {


}

