/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.SessionPutRequestBookDto
import com.ivangarzab.kluvs.api.models.SessionPutRequestSessionMembersInnerDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param clubId 
 * @param dueDate 
 * @param book 
 * @param sessionMembers Upsert participation flags for session members. Reading members have their book moved to the \"currently_reading\" shelf; opted-out members have their session-derived \"currently_reading\" shelf entry removed. If this is the only field provided (alongside `id`), any club member may make this request; otherwise owner/admin is required.
 * @param finish If true, marks the session as finished (active -> finished, idempotent guard returns 400 if already finished), increments books_read for all session_members with is_reading=true, and moves their book to the \"read\" shelf. When provided as true, this is handled as a standalone action and short-circuits other updates in the same request.
 * @param discussions Reserved for future use. Currently only checked for presence to determine the required role (owner/admin) for this request; no discussion records are created, updated, or deleted by this endpoint.
 * @param discussionIdsToDelete Reserved for future use. Currently only checked for presence to determine the required role (owner/admin) for this request; no discussion records are deleted by this endpoint.
 */
@Serializable@Serializable

data class SessionPutRequestDto (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "club_id") val clubId: kotlin.String? = null,

    @SerialName(value = "due_date") val dueDate: kotlin.String? = null,

    @SerialName(value = "book") val book: SessionPutRequestBookDto? = null,

    /* Upsert participation flags for session members. Reading members have their book moved to the \"currently_reading\" shelf; opted-out members have their session-derived \"currently_reading\" shelf entry removed. If this is the only field provided (alongside `id`), any club member may make this request; otherwise owner/admin is required. */
    @SerialName(value = "session_members") val sessionMembers: kotlin.collections.List<SessionPutRequestSessionMembersInnerDto>? = null,

    /* If true, marks the session as finished (active -> finished, idempotent guard returns 400 if already finished), increments books_read for all session_members with is_reading=true, and moves their book to the \"read\" shelf. When provided as true, this is handled as a standalone action and short-circuits other updates in the same request. */
    @SerialName(value = "finish") val finish: kotlin.Boolean? = null,

    /* Reserved for future use. Currently only checked for presence to determine the required role (owner/admin) for this request; no discussion records are created, updated, or deleted by this endpoint. */
    @SerialName(value = "discussions") val discussions: kotlin.collections.List<kotlin.String>? = null,

    /* Reserved for future use. Currently only checked for presence to determine the required role (owner/admin) for this request; no discussion records are deleted by this endpoint. */
    @SerialName(value = "discussion_ids_to_delete") val discussionIdsToDelete: kotlin.collections.List<kotlin.String>? = null

) {


}

