/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param title 
 * @param author 
 * @param imageUrl 
 */
@Serializable@Serializable

data class SessionReadingLogBookDto (

    @SerialName(value = "id") val id: kotlin.Int? = null,

    @SerialName(value = "title") val title: kotlin.String? = null,

    @SerialName(value = "author") val author: kotlin.String? = null,

    @SerialName(value = "image_url") val imageUrl: kotlin.String? = null

) {


}

