/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.SessionUpdateFlagsDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response for general field updates
 *
 * @param success 
 * @param message 
 * @param updates 
 */
@Serializable

data class SessionGeneralUpdateResponseDto (

    @SerialName(value = "success") val success: kotlin.Boolean? = null,

    @SerialName(value = "message") val message: kotlin.String? = null,

    @SerialName(value = "updates") val updates: SessionUpdateFlagsDto? = null

) {


}

