/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.BookDto
import com.ivangarzab.kluvs.api.models.ShelfStatusDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param shelf 
 * @param updatedAt 
 * @param source 
 * @param book 
 */
@Serializable@Serializable

data class ShelfEntryDto (

    @SerialName(value = "shelf") val shelf: ShelfStatusDto? = null,

    @SerialName(value = "updated_at") val updatedAt: kotlin.String? = null,

    @SerialName(value = "source") val source: ShelfEntryDto.Source? = null,

    @SerialName(value = "book") val book: BookDto? = null

) {

    /**
     * 
     *
     * Values: manual,session
     */
    @Serializable
    enum class Source(val value: kotlin.String) {
        @SerialName(value = "manual") manual("manual"),
        @SerialName(value = "session") session("session");
    }

}

