/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.ShelfStatusDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param bookId Local DB book ID
 * @param shelf 
 */
@Serializable

data class ShelfAssignRequestDto (

    /* Local DB book ID */
    @SerialName(value = "book_id") @Required val bookId: kotlin.Int,

    @SerialName(value = "shelf") @Required val shelf: ShelfStatusDto

) {


}

