/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*

/**
 * 
 *
 * Values: want_to_read,read,not_finished,currently_reading
 */
@Serializable
enum class ShelfStatusDto(val value: kotlin.String) {

    @SerialName(value = "want_to_read")
    want_to_read("want_to_read"),

    @SerialName(value = "read")
    read("read"),

    @SerialName(value = "not_finished")
    not_finished("not_finished"),

    @SerialName(value = "currently_reading")
    currently_reading("currently_reading");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ShelfStatusDto) "$data" else null

        /**
         * Returns a valid [ShelfStatusDto] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ShelfStatusDto? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

