/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.ShelfGet200ResponseOneOf1Dto
import com.ivangarzab.kluvs.api.models.ShelfGet200ResponseOneOfDto
import com.ivangarzab.kluvs.api.models.ShelfGet200ResponseOneOfShelvesInnerDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param success 
 * @param shelves 
 * @param shelf 
 */
@Serializable@Serializable

data class ShelfGet200ResponseDto (

    @SerialName(value = "success") val success: kotlin.Boolean? = null,

    @SerialName(value = "shelves") val shelves: kotlin.collections.List<ShelfGet200ResponseOneOfShelvesInnerDto>? = null,

    @SerialName(value = "shelf") val shelf: ShelfGet200ResponseDto.Shelf? = null

) {

    /**
     * 
     *
     * Values: want_to_read,read,not_finished,currently_reading
     */
    @Serializable
    enum class Shelf(val value: kotlin.String) {
        @SerialName(value = "want_to_read") want_to_read("want_to_read"),
        @SerialName(value = "read") read("read"),
        @SerialName(value = "not_finished") not_finished("not_finished"),
        @SerialName(value = "currently_reading") currently_reading("currently_reading");
    }

}

