/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.BookDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param shelf 
 * @param updatedAt 
 * @param source 
 * @param book 
 */
@Serializable@Serializable

data class ShelfGet200ResponseOneOfShelvesInnerDto (

    @SerialName(value = "shelf") val shelf: ShelfGet200ResponseOneOfShelvesInnerDto.Shelf? = null,

    @SerialName(value = "updated_at") val updatedAt: kotlin.String? = null,

    @SerialName(value = "source") val source: ShelfGet200ResponseOneOfShelvesInnerDto.Source? = null,

    @SerialName(value = "book") val book: BookDto? = null

) {

    /**
     * 
     *
     * Values: want_to_read,read,not_finished,currently_reading
     */
    @Serializable
    enum class Shelf(val value: kotlin.String) {
        @SerialName(value = "want_to_read") want_to_read("want_to_read"),
        @SerialName(value = "read") read("read"),
        @SerialName(value = "not_finished") not_finished("not_finished"),
        @SerialName(value = "currently_reading") currently_reading("currently_reading");
    }
    /**
     * 
     *
     * Values: manual,session
     */
    @Serializable
    enum class Source(val value: kotlin.String) {
        @SerialName(value = "manual") manual("manual"),
        @SerialName(value = "session") session("session");
    }

}

