/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param bookId Local DB book ID
 * @param shelf 
 */
@Serializable@Serializable

data class ShelfPostRequestDto (

    /* Local DB book ID */
    @SerialName(value = "book_id") @Required val bookId: kotlin.Int,

    @SerialName(value = "shelf") @Required val shelf: ShelfPostRequestDto.Shelf

) {

    /**
     * 
     *
     * Values: want_to_read,read,not_finished,currently_reading
     */
    @Serializable
    enum class Shelf(val value: kotlin.String) {
        @SerialName(value = "want_to_read") want_to_read("want_to_read"),
        @SerialName(value = "read") read("read"),
        @SerialName(value = "not_finished") not_finished("not_finished"),
        @SerialName(value = "currently_reading") currently_reading("currently_reading");
    }

}

