/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.SessionFinishResponseDto
import com.ivangarzab.kluvs.api.models.SessionGeneralUpdateResponseDto
import com.ivangarzab.kluvs.api.models.SessionNoChangesResponseDto
import com.ivangarzab.kluvs.api.models.SessionUpdateFlagsDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param success 
 * @param message 
 * @param membersCredited Number of is_reading session_members whose books_read count was incremented
 * @param updates 
 */
@Serializable

data class UpdateSession200ResponseDto (

    @SerialName(value = "success") val success: kotlin.Boolean? = null,

    @SerialName(value = "message") val message: kotlin.String? = null,

    /* Number of is_reading session_members whose books_read count was incremented */
    @SerialName(value = "members_credited") val membersCredited: kotlin.Int? = null,

    @SerialName(value = "updates") val updates: SessionUpdateFlagsDto? = null

) {


}

