/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.MemberAddToClubResponseDto
import com.ivangarzab.kluvs.api.models.MemberDto
import com.ivangarzab.kluvs.api.models.MemberUpdateResponseDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param success 
 * @param message 
 * @param member 
 * @param clubsUpdated 
 * @param rolesUpdated 
 * @param memberId 
 * @param clubId 
 */
@Serializable@Serializable

data class UpdateMember200ResponseDto (

    @SerialName(value = "success") val success: kotlin.Boolean? = null,

    @SerialName(value = "message") val message: kotlin.String? = null,

    @SerialName(value = "member") val member: MemberDto? = null,

    @SerialName(value = "clubs_updated") val clubsUpdated: kotlin.Boolean? = null,

    @SerialName(value = "roles_updated") val rolesUpdated: kotlin.Boolean? = null,

    @SerialName(value = "member_id") val memberId: kotlin.Int? = null,

    @SerialName(value = "club_id") val clubId: kotlin.String? = null

) {


}

