/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param memberId 
 * @param bookId 
 * @param createdAt 
 */
@Serializable@Serializable

data class UserBookLikeDto (

    @SerialName(value = "member_id") @Required val memberId: kotlin.Int,

    @SerialName(value = "book_id") @Required val bookId: kotlin.Int,

    @SerialName(value = "created_at") @Required val createdAt: kotlin.String

) {


}

