/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ivangarzab.kluvs.api.models

import com.ivangarzab.kluvs.api.models.BookDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param memberId 
 * @param bookId 
 * @param shelf 
 * @param source How the shelf was set — 'manual' (via /shelf) or 'session' (auto-synced from session/discussion participation)
 * @param updatedAt 
 * @param book 
 */
@Serializable@Serializable

data class UserBookShelfDto (

    @SerialName(value = "member_id") @Required val memberId: kotlin.Int,

    @SerialName(value = "book_id") @Required val bookId: kotlin.Int,

    @SerialName(value = "shelf") @Required val shelf: UserBookShelfDto.Shelf,

    /* How the shelf was set — 'manual' (via /shelf) or 'session' (auto-synced from session/discussion participation) */
    @SerialName(value = "source") @Required val source: UserBookShelfDto.Source = Source.manual,

    @SerialName(value = "updated_at") @Required val updatedAt: kotlin.String,

    @SerialName(value = "book") val book: BookDto? = null

) {

    /**
     * 
     *
     * Values: want_to_read,read,not_finished,currently_reading
     */
    @Serializable
    enum class Shelf(val value: kotlin.String) {
        @SerialName(value = "want_to_read") want_to_read("want_to_read"),
        @SerialName(value = "read") read("read"),
        @SerialName(value = "not_finished") not_finished("not_finished"),
        @SerialName(value = "currently_reading") currently_reading("currently_reading");
    }
    /**
     * How the shelf was set — 'manual' (via /shelf) or 'session' (auto-synced from session/discussion participation)
     *
     * Values: manual,session
     */
    @Serializable
    enum class Source(val value: kotlin.String) {
        @SerialName(value = "manual") manual("manual"),
        @SerialName(value = "session") session("session");
    }

}

